### ISSUE TITLE
[CNRWB][Tracking Issue] Cloud Native Research Workloads Book

### ISSUE THREAD

**Issue by mrbobbytables** [cncf/research-user-group#16]
One of the key areas identified by the CNCF Research User Group (RUG) for improvement<sup>1</sup> has been in the realm of documentation and best practices for running Research Workloads in a _"Cloud Native"_ way; or - on top of Kubernetes.

Taking inspiration from the Scientific OpenStack Community<sup>2</sup>, RUG has decided to do something similar and put together a book of user stories and best practices.

The complete break down of chapters and topics is still open for additions or modifications, but the current break down includes:
- Cluster Operations:
  - [Broad configuration management + cluster-lifecycle](https://github.com/cncf/research-user-group/issues/17)
  - [Management of clusters on top of OpenStack](https://github.com/cncf/research-user-group/issues/18)
  - [Integration with Parallel / HPC file systems and access management](https://github.com/cncf/research-user-group/issues/19)
  - [Managing / Exposing GPUs](https://github.com/cncf/research-user-group/issues/20)
  - [Large Scale Clusters (1000+ nodes)](https://github.com/cncf/research-user-group/issues/21)
- Making Research Cloud Native:
  - [Scalable JupyterHub](https://github.com/cncf/research-user-group/issues/22)
  - [KubeFlow / ML lifecycle](https://github.com/cncf/research-user-group/issues/23)
  - [Batch / MPI](https://github.com/cncf/research-user-group/issues/24)
  - [Workflows / Workflow Engines / GitOps](https://github.com/cncf/research-user-group/issues/25)
  - [DataOps (Data lifecycle management)](https://github.com/cncf/research-user-group/issues/26)

(_Will link to break out issues as they're made_)

Until a better acronym can be decided, issues related to this effort will be prefixed with CNRWB ("**C**loud **N**ative **R**esearch **W**orkloads **B**ook").

[1] [CNCF Research User Group KubeCon NA 2019 Survey](https://github.com/cncf/research-user-group/blob/master/events/2019/KCCNCNA/RUG-Survey-Summary.pdf)
[2] [Crossroads of Cloud and HPC: OpenStack for Scientific Research](https://object-storage-ca-ymq-1.vexxhost.net/swift/v1/6e4619c416ff4bd19e1c087f27a43eea/www-assets-prod/science/OpenStack-CloudandHPC6x9Booklet-v4-online.pdf)

**Comment by rochaporto** [comment]
We're closing these tickets for now, as we work in recipes for topics coming out of the regular meetings. Can check later if it makes sense to pick it up again.
