### ISSUE TITLE
[CNRWB] Configuration Management / Cluster Lifecycle

### ISSUE THREAD

**Issue by mrbobbytables** [cncf/research-user-group#17]
Best practices around provisioning and managing clusters.
- What tooling works well for provisioning (metal^3, kubespray, cluster-api etc)
- How is authn/authz handled
- base security policy for multi-user (OPA?)

**Comment by rochaporto** [comment]
We're closing these tickets for now, as we work in recipes for topics coming out of the regular meetings. Can check later if it makes sense to pick it up again.
