### ISSUE TITLE
[CNRWB] Scalable JupyterHub

### ISSUE THREAD

**Issue by mrbobbytables** [cncf/research-user-group#22]
JupyterHub is one of the most frequently installed applications for research sites, and is often the first thing users spin up. Guidance on provisioning and integrating with various identity systems (e.g. LDAP) would be useful. There is prior-art with the very well put together [zero-to-jupyterhub](https://zero-to-jupyterhub.readthedocs.io/en/latest/) project.

**Comment by rochaporto** [comment]
We're closing these tickets for now, as we work in recipes for topics coming out of the regular meetings. Can check later if it makes sense to pick it up again.
