### ISSUE TITLE
[CNRWB] KubeFlow / ML Lifecycle

### ISSUE THREAD

**Issue by mrbobbytables** [cncf/research-user-group#23]
KubeFlow has become the go-to for it's comprehensive inclusion of the numerous tools used for ML training and model publishing. Best practices for managing it, especially in a multi-user environment would be worthwhile.

**Comment by rochaporto** [comment]
We're closing these tickets for now, as we work in recipes for topics coming out of the regular meetings. Can check later if it makes sense to pick it up again.
