### ISSUE TITLE
[CNRWB] Batch Workloads / MPI

### ISSUE THREAD

**Issue by mrbobbytables** [cncf/research-user-group#24]
Guidance on running batch workloads, and specifically MPI on top of Kubernetes.
Useful resources:
- [volcano](https://volcano.sh/)
- [kube-batch](https://github.com/kubernetes-sigs/kube-batch)
- [mpi-operator](https://github.com/kubeflow/mpi-operator)

**Comment by ArangoGutierrez** [comment]
+1

**Comment by rochaporto** [comment]
We're closing these tickets for now, as we work in recipes for topics coming out of the regular meetings. Can check later if it makes sense to pick it up again.
