### ISSUE TITLE
[CNRWB] Workflows / Workflow Engines / GitOps

### ISSUE THREAD

**Issue by mrbobbytables** [cncf/research-user-group#25]
What are the common workflow engines that are used, why are they used. 
- [argo](https://argoproj.github.io/)
- [kale](https://github.com/kubeflow-kale/kale)
- [commonwl](https://www.commonwl.org/)

**Note:** GitOps was originally grouped in with this with the idea of making git the source of truth, it might be worth its own break out or focused on GitOps for workflows specifically.

**Comment by mr-c** [comment]
https://s.apache.org/existing-workflow-systems

**Comment by pditommaso** [comment]
It depends the context: CI, ETL, data analytics, computational research, etc. I guess you are mostly interested in the latter.

**Comment by rochaporto** [comment]
I think it's worth splitting gitops and workflows.

For gitops we're using Flux mainly but some users also relying on ArgoCD, and interested in the ongoing work for a common gitops-engine:
https://blog.argoproj.io/argo-cd-v1-6-democratizing-gitops-with-gitops-engine-5a17cfc87d62

**Comment by rochaporto** [comment]
We're closing these tickets for now, as we work in recipes for topics coming out of the regular meetings. Can check later if it makes sense to pick it up again.
