### ISSUE TITLE
[CNRWB] DataOps

### ISSUE THREAD

**Issue by mrbobbytables** [cncf/research-user-group#26]
Managing data in a Cloud Native environment has its own set of challenges that are fundamentally different from "classic" HPC environments. There is much more reliance on object storage etc. What are the best practices around this change? How do you manage the lifecycle of data?

This could be expanded more into the operations category for on-prem deployments of ceph or grouped in with the parallel filesystems a bit.

**Comment by rochaporto** [comment]
We're closing these tickets for now, as we work in recipes for topics coming out of the regular meetings. Can check later if it makes sense to pick it up again.
