### ISSUE TITLE
Rotation calendar links in the readme don't work

### ISSUE THREAD

**Issue by lfdversluis** [cncf/research-user-group#27]
The links for rotation 2 and 3 don't work. If I click on them I see that the requested meeting does not exist. 

For reference, this is the URL to rotation 2: https://calendar.google.com/event?action=TEMPLATE&tmeid=NWs5c3I0bWxqMW9yb20wb3JzOXBpaHNmcnRfMjAyMDAxMjJUMTgwMDAwWiBya2lsbGVuQHVtaWNoLmVkdQ&tmsrc=rkillen%40umich.edu&scp=ALL

**Comment by mrbobbytables** [comment]
hmm 🤔 I generated the links from the `publish event` drop down. I wonder if I don't technically have the rights to?

@oicheryl do you have an idea? Maybe you need to as the event owner?
