### ISSUE TITLE
How can I change the invite links?

### ISSUE THREAD

**Issue by stackedsax** [cncf/research-user-group#37]
The first two links in this repo's README are incorrect, but I don't know how to fix them.

Specifically, this line with these two links:
> Calls on the [first Wednesday](https://calendar.google.com/event?action=TEMPLATE&tmeid=NXRxaGM4bnRranJtOTg1N2M2ZXJsb2ZsOWlfMjAyMDEwMDdUMTUwMDAwWiBsaW51eGZvdW5kYXRpb24ub3JnX281YXZqbHZ0MmNhZTlicTdhOTVlbWM0NzQwQGc&tmsrc=linuxfoundation.org_o5avjlvt2cae9bq7a95emc4740%40group.calendar.google.com&scp=ALL) and [third Wednesday](https://calendar.google.com/event?action=TEMPLATE&tmeid=NmswcXZhcjdscXVzODZtM3MwaTc1MHBnbzdfMjAyMDA5MTZUMTUwMDAwWiBsaW51eGZvdW5kYXRpb24ub3JnX281YXZqbHZ0MmNhZTlicTdhOTVlbWM0NzQwQGc&tmsrc=linuxfoundation.org_o5avjlvt2cae9bq7a95emc4740%40group.calendar.google.com&scp=ALL) of each month at 8:00 PT.

The resulting invites point people to the Zoom call which we no longer use.  I'd like to point everyone to the Bevy platform instead.

@rochaporto, how did you create these calendar templates we're using in these links?  I'll create new links and update the README if I can.

**Comment by onlydole** [comment]
Howdy, @stackedsax! Does [this PR](https://github.com/cncf/research-user-group/pull/38) address your concerns, or are there any other items that would be helpful in the README?

**Comment by rochaporto** [comment]
Thanks @onlydole . I did not create these, we kept wondering how people still went to the old zoom call. Mystery solved.

**Comment by onlydole** [comment]
Ah! I’m always glad once a mystery gets solved 😄 Thank you both!

**Comment by stackedsax** [comment]
Yes, thanks, @onlydole!
